
BEGIN;

DELETE FROM assignto
WHERE eid IN (
    SELECT eid FROM EMPLOYEE
    WHERE eid NOT IN (SELECT eid FROM SCHEDULE WHERE eid IS NOT NULL)
);

DELETE FROM HAS
WHERE eid IN (
    SELECT eid FROM EMPLOYEE
    WHERE eid NOT IN (SELECT eid FROM SCHEDULE WHERE eid IS NOT NULL)
);

DELETE FROM PARTICIPATE
WHERE eid IN (
    SELECT eid FROM EMPLOYEE
    WHERE eid NOT IN (SELECT eid FROM SCHEDULE WHERE eid IS NOT NULL)
);

DELETE FROM EMPLOYEE
WHERE eid NOT IN (
    SELECT eid FROM SCHEDULE WHERE eid IS NOT NULL
);

COMMIT;

rollback;